name: expenseflow
description: Multi-user expense tracker with smart alerts, analytics, and local persistence.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Charts
  fl_chart: ^0.68.0

  # CSV export
  csv: ^6.0.0

  # File paths (local persistence)
  path_provider: ^2.1.2

  # Cool fonts via Google Fonts
  google_fonts: ^6.1.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
